service: aws-dad-teste
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"


functions:
  hello:
    handler: dad.hello
    events:
      - http:
          path: hello
          method: get

  calcularMedia:
    handler: dad.calcularMedia
    events:
      - http:
          path: calcularMedia
          method: post
          cors: true